var StringResources = {

    menus: {
        highScore: "High Score",
        loading: "loading",
        score: "score",
        level: "level",
        options: "options",
        highJelly: "High Jelly",
        gameOver: "GAME OVER",
        jellypedia: "Jellypedia",
        pause: "paused",
        sound: "Sound",
        menu: "menu",
        leaderboards: "Leaderboards",
        reset: "Reset All Data",
        restore: "Restore",
        restoreWarning: "It will restore your purchases from store, Continue?",
        resetWarning: "Are you sure. All you progress will be lost",
        about: "About",
        aboutText: "Develop by",
        aboutURL: "www.dia-studio.com",
        tutorial: "Tutorial",
        shop: "shop",
        playerName: "Player Name",
        playerNameDesc: "Type your name for the leaderboards.",
        error: "Sorry, Something went wrong",
        rating: "Rate us",
        ratingDesc: "Are you enjoying?\nPlease rate us",
        like: "Like us",
        share: "Share",
        watchVideo: "Watch Video",
        gift: "gift in @ minutes",

    },
    tutorial: {
        msgheplme: "Help me to evolve\nJoin  2 identical jellies.",
        msgOnceMore: "Great! now I'm bigger, \nevolve me once more",
        msgDirt: "Oh no, a dirt appears \n Join a jelly here to destroy it.",
        msgPlay: "Perfect!\nNow evolve me to the max!",
        msgItemClean: "You can always use items.\n this cleans the board",
        msgItemFast: "this one join some jellies",
        msgItemTime: "this one make time slower",
        msgItemRevive: "if you loose, use this to revive",
        msgBoardFill: "but be careful, \ndo not let the board fill, \nthis is the end for us.",

    },
    jellies: {
        1: { name: "Little Jelly", description: "Small but essential" },
        2: { name: "Droplet", description: "Dripping everywhere" },
        4: { name: "Little Cake", description: "Incredible Lemon \nflavor" },
        8: { name: "Yolk", description: "She misses the\nMr. White..." },
        16: { name: "SunBronze", description: "With tanned little \nbody" },
        32: { name: "Strawberry", description: "Bored from jellying" },
        64: { name: "Upsety", description: "'Don't touch me...'" },
        128: { name: "Sluggjelly", description: "The sluggish Jelly" },
        256: { name: "Moti", description: "Irresistible desire to \neat with soy sauce" },
        512: { name: "Big cheeks", description: "Reminds me of my\nbrother cheeks" },
        1024: { name: "Geleialien", description: "Came from another\nplanet to jam" },
        2048: { name: "Oil", description: "An oil droplet" },
        4096: { name: "Healthy", description: "Your personal \nhealth jelly" },
        8192: { name: "Cuboid", description: "This one born boxy." },
        16384: { name: "Lumpy Jelly", description: "Bad tempered and \nlumpy" },
        32768: { name: "Sonic Jelly", description: "A very fast one" },
        65536: { name: "Super Sayajelly", description: "The strongest jelly \nof the universe" },
    },
    items: {
        clean: "Clean",
        fast: "Fast",
        time: "Time",
        revive: "Revive",
        evolve: "Evolve",
    },
    store: {
        title: "Store",
        clean: {
            name: "Clean 3x",
            desc: "Remove all dirt and small jellies",
        },
        fast: {
            name: "Fast 3x",
            desc: "Join 5 avaliable jellies",
        },
        time: {
            name: "Freeze Time 3x",
            desc: "Freeze times for 5 seconds",
        },
        revive: {
            name: "Revive 3x",
            desc: "Return to play after losing",
        },
        lucky: {
            name: "Lucky clover",
            desc: "Doubles the chance of finding an item",
        },
        pack: {
            name: "Item Pack",
            desc: "A package with 3 units of each item",
        },
    },
    credit: {
    },

    social: {
        shareDescription: "Help the jellie neighbourhood to evolve and eliminate your monster enemies! Join equal jellies to see new characters. The more jellies evolved more discoveries! But beware, be aware that the enemy has power over time and his henchmen.Many jellies want to help, many came from far away to fight, but you need to be fast for it to be organized before the desperation defeat you.",
        shareTitle: "JoinJelly",
        shareCaption: "Hi!",
    }
}

var StringResources_pt = {

    menus: {
        highScore: "Recorde",
        loading: "Carregando",
        score: "Pontos",
        level: "level",
        options: "opções",
        highJelly: "maior",
        gameOver: "GAME OVER",
        jellypedia: "Jellypedia",
        pause: "pausa",
        sound: "Sons",
        menu: "Menu",
        leaderboards: "Placar",
        reset: "Apagar tudo",
        restore: "Recuperar",
        restoreWarning: "Isso vai recuperar suas compras da loja, quer continuar?",
        resetWarning: "Você tem certeza? tudo que voce consquistou será perdido.",
        about: "Sobre",
        aboutText: "Desenvolvido por",
        aboutURL: "www.dia-studio.com",
        tutorial: "Tutorial",
        shop: "Compras",
        playerName: "Nome do Jogador",
        playerNameDesc: "Digite seu nome para aparecer no placar dos melhores",
        error: "Desculpe, algo deu errado.",
        rating: "Avaliação",
        ratingDesc: "Está gostando? \nNos Ajude. Dê sua avaliação",
        like: "Curtir",
        share: "Compartilhar",
        watchVideo: "Veja um Video",
        gift: "vídeo em @ min",
    },
    tutorial: {
        msgheplme: "Me ajude a evoluir\nJunte 2 geleias IGUAIS.",
        msgOnceMore: "Legal! Estou maior, \nMe desenvolva novamente",
        msgDirt: "Oh não, sujeira! Junte \numa geleia aqui para limpar.",
        msgPlay: "Perfeito!\nMe evolua ao maximo!",
        msgItemClean: "Sempre que precisar use \nitems. Este limpa a bagunça",
        msgItemFast: "Esse junta \nalgumas geleias",
        msgItemTime: "Esse congela o tempo",
        msgItemRevive: "Se voce perder, use este para reviver",
        msgBoardFill: "Mas Tenha cuidado, se acabar \nos espaços no chão é o fim.",

    },
    jellies: {
        1: { name: "Geleinha", description: "Pequena mas \nimportante" },
        2: { name: "Gotinha", description: "gotejando por\ntodo lado" },
        4: { name: "Bolinho", description: "Incrível sabor de\nLimão" },
        8: { name: "Gema", description: "Sente falta da\nClara..." },
        16: { name: "SunBronze", description: "Com corpinho \nbronzeado" },
        32: { name: "Morango", description: "Entediada de tanto\ngelatinar" },
        64: { name: "Chatinha", description: "Não gosta de ser \ntocada" },
        128: { name: "Gelerda", description: "A geleia lerdinha" },
        256: { name: "Moti", description: "Irresistível vontade\nde comer com shoyu" },
        512: { name: "Xexão", description: "Lembra as bochechas \ndo meu irmão" },
        1024: { name: "Geleialien", description: "Veio de outro \nplaneta para geleiar" },
        2048: { name: "Petróleo", description: "Uma gotinha de \nóleo" },
        4096: { name: "Saudável", description: "Sua geleia pessoal \nde saúde" },
        8192: { name: "Cuboide", description: "Esse nasceu\nquadradão." },
        16384: { name: "Geleia Caroço", description: "Mau humorada e \nencaroçada" },
        32768: { name: "Geleia Sonica", description: "Uma geleia\nmuito rápida" },
        65536: { name: "Super Sayajelly", description: "A geleia mais forte \ndo universo" },

        131072: { name: "Phanton6 Jelly", description: "description" },
        262144: { name: "Phanton6 Jelly", description: "" },
    },
    items: {
        clean: "Limpa",
        fast: "Rápido",
        time: "Tempo",
        revive: "Reviver",
        evolve: "Desenvolve",
    },
    store: {
        title: "Loja",
        clean: {
            name: "Limpar 3x",
            desc: "Limpa sujeira e geleinhas",
        },
        fast: {
            name: "Rápido 3x",
            desc: "Junta algumas geleias",
        },
        time: {
            name: "Tempo 3x",
            desc: "para o tempo por 5 segundos",
        },
        revive: {
            name: "Reviver 3x",
            desc: "Retorne a jogar depis que perder.",
        },
        lucky: {
            name: "Trevo da Sorte",
            desc: "Dobra a chance de encontrar items",
        },
        pack: {
            name: "Pacotinho",
            desc: "Contem 5 items de cada",
        },
        gibpack: {
            name: "Pacotão",
            desc: "Contem 10 items de cada.",
        },
    },
    credit: {
    },
    social: {
        shareDescription: "Ajude a comunidade geleística a evoluir e  eliminar seus inimigos! Junte geleias iguais para evoluir e doscrobrir novos personagens. Quanto mais geleias evoluídas mais descobertas! Mas cuidado, você verá que o inimigo tem poder sobre o tempo e seus capangas. Muitas geleias querem ajudar, muitas vieram de longe para o combate.  Mas seja rápido antes que o desespero o derrote!.!",
        shareTitle: "Join Jelly",
        shareCaption: "Hi",
    }

}